Convert some experimental SSB URIs to actions
ssb-ngi-pointer/ssb-uri-spec pull request #1
Opened 2021-03-10 13:06 UTC by staltz

2021-03-10 13:47 UTC, cryptix commented
Thanks! That looks much more workable to me.

For people following along, my concern was that differentiating a `msaddr` from a `roomInvite` can just be done by checking that it has more candidate `key=value` pairs. And then for me the next step is that the set of `(key1, key2, key3)` has to be unique to do a clean mapping. Which seems tricky if we want other people to use and build on this.

2021-03-10 13:47 UTC, cryptix commented
Nickpick: `action=consume-alias` should maybe be `consume-room-alias`? but I guess we can take these specifics to the room2 doc and keep it generic here.

2021-03-10 13:54 UTC, cryptix requested changes
the single msaddr should have one, too

2021-03-10 13:54 UTC, cryptix commented on readme.md
>    - `ssb:?msaddr=<MSADDRESS>`
```suggestion
  - `ssb:?action=add-pub&msaddr=<MSADDRESS>`
```

2021-03-10 13:58 UTC, staltz commented on readme.md
>    - `ssb:?msaddr=<MSADDRESS>`
This one I disagree, I think there is no action implicit in traditional multiserver addresses (e.g. passing `net:example.com:8008~shs:thekey` around), and this is the purpose of `ssb:?msaddr=<MSADDRESS>`. Similarly, there is no action implicit in `ssb:message:sha256:<MSGID>`, it's not `ssb:?action=open-msg&ref=message:sha256:<MSGID>`. URIs are useful to simply identify stuff, and here we are identifying the address of a peer.

2021-03-10 14:01 UTC, cryptix commented on readme.md
>    - `ssb:?msaddr=<MSADDRESS>`
:shrug: I don't understand that, sorry.

For me all these have to have an intent since the idea is to trigger action in other apps. I was just trying to make those actions it explicit.

2021-03-10 14:06 UTC, cryptix commented on readme.md
>    - `ssb:?msaddr=<MSADDRESS>`
I can see that there is different ways of using a thing and maybe those are then other things then `action`s, maybe. Maybe we have an `info=multiserver-address` then on these.

To me this all seems very much like a message passing system, tho.

2021-03-10 14:12 UTC, staltz commented on readme.md
>    - `ssb:?msaddr=<MSADDRESS>`
This is just what URIs are. Maybe to focus the discussion, would you advocate for `ssb:message:sha256:<MSGID>` or for `ssb:?action=open-msg&ref=message:sha256:<MSGID>`?

Similarly, web URLs don't specify the "action" (the HTTP method), it's left open to browsers whether they will do a GET or a HEAD. Typically, it's GET. But the URL itself doesn't prevent apps from choosing to do a HEAD request.

Point is: apps interpret how to consume URIs/URLs, it's not up to the URI to fully specify how it should be consumed. That's because URIs are identifiers (think "names"), not RPCs.

2021-03-10 15:43 UTC, staltz commented on readme.md
>    - `ssb:?msaddr=<MSADDRESS>`
Sorry if the comment above wasn't helpful. I'm thinking in different terms, now, which may intersect with your concerns:

The canonical URIs have a "type" identifier embedded in them:

```
ssb:<TYPE>:<ALG>:<ID>
```

Where `<TYPE>` is (so far):

- `message`
- `feed`
- `blob`

The reason why we need `<TYPE>` is that SSB URIs can specify content of different types (feeds are very different from messages), while other URIs schemes are simpler because they specify only one type of resource (e.g. `tel:<phonenumber>`). So in the future, if we would canonicalize multiserver addresses (just a hypothetical!), it could be:

```
ssb:address:multiserver:<MSADDRESS>
```

Where `address = <TYPE>`, `multiserver = <ALG>`. Meanwhile, our experimental URI `ssb:?msaddr=<MSADDRESS>` doesn't have `<TYPE>`/`<ALG>`/`<MSADDRESS>`. So maybe  this fits within your original argument, that for *both* canonical and experimental URIs we should have `<TYPE>`/`<ALG>`/`<ID>`. That's something I can get behind, and while it might not be exactly `ssb:?action=add-pub&msaddr=<MSADDRESS>` it could use something like a `info` or `type` (and/or `alg`) query parameters. I'll think about this.

2021-03-16 09:56 UTC, staltz commented on readme.md
>    - `ssb:?msaddr=<MSADDRESS>`
- `ssb:?action=join-room&msaddr=<MSADDRESS>&invite=<CODE>`
  - `ssb:?action=consume-alias&alias=<A>&userId=<UID>&signature=<SIG>&msaddr=<MSADDRESS>&roomId=<RID>`
  - `ssb:?action=start-http-auth&sid=<SID>&sc=<SC>`

2021-03-16 09:57 UTC, staltz commented on readme.md
>    - `ssb:?msaddr=<MSADDRESS>`
- `ssb:address:multiserver:<MSADDRESS>`

2021-03-16 10:00 UTC, staltz commented on readme.md
>    - `ssb:?msaddr=<MSADDRESS>`
- `ssb:address:multiserver?msaddr=<MSADDRESS>`

2021-03-16 10:20 UTC, merged